"""
Django settings for dish project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#FLAVOURS_TEMPLATE_PREFIX = 'flavours/'
FLAVOURS = ('full', 'mobile')
#FLAVOURS_COOKIE_HTTPONLY = True
#DEFAULT_MOBILE_FLAVOUR = 'mobile'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2tx4g&d1&opwc%bw*pjoh0u5d$1r@8$#+933ae+2^gdw*)8nt$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#PROJECT_ROOT = os.path.normpath(os.path.dirname(__file__))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

MEDIA_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__),'media/'))

DIRNAME = os.path.abspath(os.path.dirname(__file__))

# Application definition

INSTALLED_APPS = (
	'django.contrib.sites',#For:django-allauth
	'allauth.account',#For:django-allauth
	'allauth.socialaccount',#For:django-allauth
	'allauth.socialaccount.providers.facebook',#For:django-allauth
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'dish.files',
	'crispy_forms',
	'django_mobile',
	'django.contrib.sitemaps',
	'inflection',
	'debug_toolbar',#For debug_toolbar
	#'ajax_select', #<=django-ajax-selects
)
SITE_ID = 1#For:django-allauth
MIDDLEWARE_CLASSES = (
	'debug_toolbar.middleware.DebugToolbarMiddleware',#For debug_toolbar
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.BrokenLinkEmailsMiddleware', #To send 404 'page not found' error to ADMINS
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django_mobile.middleware.MobileDetectionMiddleware',
	'django_mobile.cache.middleware.CacheFlavourMiddleware',
	'django.middleware.cache.FetchFromCacheMiddleware',
	'django_mobile.middleware.SetFlavourMiddleware',
)

ROOT_URLCONF = 'dish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [os.path.join(PROJECT_ROOT,'templates'),os.path.join(PROJECT_ROOT,'templates')],
		'DIRS': [os.path.join(PROJECT_ROOT,'templates')],
		#'DIRS': [],
		#'APP_DIRS': True,
        #'APP_DIRS': False, #Because django_mobile
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',#Also for:django-allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_mobile.context_processors.flavour',
				'dish.files.context_processors.global_constants',# By me: for global_constants
            ],
            'loaders':[
				('django_mobile.loader.CachedLoader', [
					'django_mobile.loader.Loader',
					'django.template.loaders.filesystem.Loader',
					'django.template.loaders.app_directories.Loader',
					]),
			],
        },
    }]

INTERNAL_IPS = ('127.0.0.1','localhost')#For debug_toolbar

WSGI_APPLICATION = 'dish.wsgi.application'

BASE_URL = 'http://localhost:8000/' # By me: for global_constants

##Start for:django-allauth
LOGIN_REDIRECT_URL = '/myprofile/'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
##ACCOUNT_ADAPTER = 'dish.files.allauth_adapter.UserAccountAdapter'
##AUTH_USER_MODEL = 'dish.files.models.userProfile'
#SOCIALACCOUNT_ADAPTER = 'dish.files.allauth_adapter.MyAdapter'
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = False

ACCOUNT_EMAIL_VERIFICATION ='optional' #A e-mail verification mail will be sent.
# Required by django-allauth to extend the sign up form to include profile data
ACCOUNT_SIGNUP_FORM_CLASS = 'dish.files.forms.SignupAllauthForm'
#AUTHENTICATION_BACKENDS -> For:django-allauth
AUTHENTICATION_BACKENDS = (
	# Needed to login by username in Django admin, regardless of `allauth`
	'django.contrib.auth.backends.ModelBackend',#For:django-allauth
	# `allauth` specific authentication methods, such as login by e-mail
	'allauth.account.auth_backends.AuthenticationBackend',#For:django-allauth
)
#Alows to set social account providers scope
SOCIALACCOUNT_PROVIDERS = \
	{'facebook':
		 {'METHOD': 'oauth2',
		 'SCOPE': ['email','public_profile', 'user_friends'],
		 'AUTH_PARAMS': {'access_type': 'online'},
		 'FIELDS': ['id',
		    'email',
			'name',
			'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
		  'EXCHANGE_TOKEN': True,
		  'LOCALE_FUNC': lambda request: 'kr_KR',
		  'VERIFIED_EMAIL': False,
		  'VERSION': 'v2.4'
		  },
}
"""
SOCIALACCOUNT_PROVIDERS = \
	{'facebook':
		 {'SCOPE': ['email', ],
		  'AUTH_PARAMS': {'access_type': 'online'}
		  },
	 'google':
		 {'SCOPE': ['https://www.googleapis.com/auth/userinfo.profile',
					'email'],
		  'AUTH_PARAMS': {'access_type': 'online'}
		 },
}
"""
##End for:django-allauth

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'wfg_db',
		'USER': 'postgres',
		'PASSWORD': 'claudio',#admin?
	}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False#It was true but to avoid naive datetime using time zone I changed to false

#STATIC_ROOT = os.path.join(BASE_DIR, 'dish/static')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'dish/static'),
)

#DIRNAME = os.path.abspath(os.path.dirname(__file__))
UPLOAD_DISH = 'dish/media/dishes'
UPLOAD_USER = 'dish/media/users'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

MEDIA_URL = '/media/'

#To send emails
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'worldfoodguideapp@gmail.com'
EMAIL_HOST_PASSWORD = 'wfgpass1'
ADMINS = (('Claudio', 'itisclaudio@gmail.com'),) # A tuple that lists people who get code error notifications. When DEBUG=False